language: python
python:
  - "2.7"
  - "3.6.x"
  - "pypy"
install:
  - "pip install -r test/requirements.txt --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
  - "python setup.py develop"
script:
    python setup.py test
after_success:
    coveralls
